providers:
  flub: 
    source-path: 'tmp/feed-exports/flub.yaml'

  glorf: 
    source-path: 'tmp/feed-exports/glorf.json'

  third_provider:
    # required config for connecting to endpoint in remote source
    # providers would be here
    source-path: 'tmp/feed-exports/third_provider.json'